resources:
- dep-globex-ui.yaml
- rt-globex-ui.yaml
- sa-globex-app-globex-ui.yaml
- svc-globex-ui.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: infyartifactory.jfrog.io/ccdsdam-ocp/globex-ui
  newName: infyartifactory.jfrog.io/ccdsdam-ocp/globex-ui
  newTag: latest
